<!-- Fonts -->
<link rel="stylesheet" href="<?= $this->url('dist/font/font.css') ?>">

<!-- Fontawesome -->
<link rel="stylesheet" href="<?= $this->url('dist/font/icons/fontawesome.min.css') ?>">
<link rel="stylesheet" href="<?= $this->url('dist/font/icons/regular.min.css') ?>">
<link rel="stylesheet" href="<?= $this->url('dist/font/icons/solid.min.css') ?>">

<!-- Hamburgers -->
<link rel="stylesheet" href="<?= $this->url('dist/css/hamburgers.min.css') ?>">

<!-- Main (Load last) -->
<link rel="stylesheet" href="<?= $this->url('dist/css/main.min.css') ?>">
