<!-- Set charset -->
<meta charset="UTF-8">

<!-- Set viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Copyright and author -->
<meta name="copyright" content="&copy; Iwan van der Wal">
<meta name="author" content="Iwan van der Wal" lang="en">

<!-- Description and keywords -->
<meta name="description" content="An easy-to-use PHP, HTML, CSS, JavaScript and Sass framework!">
<meta name="keywords" content="php, html, css, javascript, sass, scss, framework, mvc">

<!-- Theme color -->
<meta name="theme-color" content="#C80810">
