<section class="error h-100 center-x">
  <div class="row">
    <div class="col center-x">
      <h1>403</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="row">
        <div class="col center-x">
          <h3>You have no access to this page.</h3>
        </div>
      </div>
      <div class="row">
        <div class="col center-x">
          <p>You will be redirected to the <a href="<?= PageController::url(REDIRECT) ?>">homepage</a>.</p>
        </div>
      </div>
    </div>
  </div>
</section>
