<section class="home">
  <span class="background"></span>
  <div class="row">
    <div class="col en home-title center-x">
      <p>Welcome to my mini-game website!</p>
    </div>
    <div class="col nl home-title center-x">
      <p>Welkom op mijn mini-game website!</p>
    </div>
  </div>
  <hr>
  <div class="row card-row">
    <a class="col en game-card card-hangman center text-center" href="<?= PageController::url('hangman') ?>">Hangman</a>
    <a class="col nl game-card card-hangman center text-center" href="<?= PageController::url('hangman') ?>">Galgje</a>
    <a class="wip col game-card card-snake center text-center" href="<?= PageController::url('snake') ?>">Snake</a>
    <a class="col en game-card card-tictactoe center text-center" href="<?= PageController::url('tictactoe') ?>">Tic Tac Toe</a>
    <a class="col nl game-card card-tictactoe center text-center" href="<?= PageController::url('tictactoe') ?>">Boter Kaas en Eieren</a>
    <a class="wip col game-card card-blackjack center text-center" href="<?= PageController::url('blackjack') ?>">Blackjack</a>
    <a class="wip col game-card card-yahtzee center text-center" href="<?= PageController::url('yahtzee') ?>">Yahtzee</a>
    <a class="wip col en game-card card-minesweeper center text-center" href="<?= PageController::url('minesweeper') ?>">Minesweeper</a>
    <a class="wip col nl game-card card-minesweeper center text-center" href="<?= PageController::url('minesweeper') ?>">Mijnenveger</a>
  </div>
  <hr>
  <div class="row">
    <div class="col en home-text center-x">
      <p>More games coming soon!</p>
    </div>
    <div class="col nl home-text center-x">
      <p>Meer spellen komen binnenkort!</p>
    </div>
  </div>
  <div class="row">
    <div class="col en home-text center-x">
      <p>Enjoy!</p>
    </div>
    <div class="col nl home-text center-x">
      <p>Veel plezier!</p>
    </div>
  </div>
</section>
